#!/usr/bin/env bash

__DEVICE="/dev/ttyUSB0"
__GPIO_PORTS=( 5 6 7 24 25 26 )

__ON=1
__OFF=0

_set_all_ports() {
    local -r _direction=$1
    for __port in "${__GPIO_PORTS[@]}"; do
        printf "gpio set %d %d\n" "$__port" "$_direction" > $__DEVICE
    done
}

_main() {
    if [[ ! -z $1 ]]; then
        __DEVICE=$1
    fi

    stty -F "$__DEVICE" 115200 cs8 -echo hupcl -ixoff -onlcr
    local __pid
    __pid=$(tail -f "$__DEVICE")

    _set_all_ports $__OFF
    sleep 0.1
    printf "Set all transistors to ON\n"
    _set_all_ports $__ON
    read -r -n 0 -p "Press Enter to continue... "
    printf "Set all transistors to OFF\n"
    _set_all_ports $__OFF
    read -r -n 1 -p "Press any key to exit... "
    kill -15 "$__pid"

    exit 0
}

_main "$@"
